service: oplata_site
image: oplata_site

servers:
  web:
    hosts:
      - 194.87.98.136

ssh:
  user: vasiliy

registry:
  server: localhost:5000
  username: dummy
  password: dummy

env:
  clear:
    RAILS_ENV: production
    PORT: 3000
    RAILS_SERVE_STATIC_FILES: "true"
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE

builder:
  arch: amd64
  dockerfile: Dockerfile

volumes:
  - "/home/vasiliy/images:home/vasiliy/Изображения/Новая папка"
proxy:  
   healthcheck:
    path: /up             # путь проверки
    interval: 5           # интервал между проверками в секундах
    timeout: 15           # таймаут ожидания ответа приложения
  
