service: oplata_site
image: oplata_site
servers:
  web:
    - 194.87.98.136
ssh:
  user: vasiliy
registry:
  server: localhost:5000
  username: dummy
  password: dummy
env:
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - RAILS_SERVE_STATIC_FILES
  clear:
    RAILS_ENV: production
    PORT: 3000

health_check:
  path: /up
  port: 3000
  interval: 5
  timeout: 3
  retries: 3