service: oplata_site
image: oplata_site

servers:
  web:
    hosts:
      - 194.87.98.136

deploy_timeout: 90

ssh:
  user: vasiliy

registry:
  server: localhost:5000
  username: dummy
  password: dummy

env:
  clear:
    RAILS_ENV: production
    PORT: 3000
    RAILS_SERVE_STATIC_FILES: "true"
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE

builder:
  arch: amd64
  dockerfile: Dockerfile

volumes:
  - "/home/vasiliy/oplata_storage:/rails/storage"
  - "/home/vasiliy/images:/home/vasiliy/images"
proxy:  
  host: 194.87.98.136
  app_port: 3000
  ssl: false
  healthcheck:
    path: /up             # путь проверки
    interval: 5           # интервал между проверками в секундах
    timeout: 3           # таймаут ожидания ответа приложения
  
